// pqc_crypto.c
// AES-256-GCM encryption and decryption implementation.
//
// Depends on: pqc_crypto.h, pqc_common.h, OpenSSL (libcrypto)

#define _POSIX_C_SOURCE 200809L

#include "pqc_crypto.h"

#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <arpa/inet.h>

#include <openssl/evp.h>
#include <openssl/rand.h>

// ============================================================================
// AES-256-GCM ENCRYPTION
// ============================================================================

int aes_gcm_encrypt(const uint8_t  key[AES_KEY_LEN],
                    const uint8_t *plaintext, int pt_len,
                    const uint8_t  iv[IV_LEN],
                    uint8_t       *ciphertext,
                    uint8_t        tag[TAG_LEN]) {

    if (!key || !plaintext || pt_len <= 0 || !iv || !ciphertext || !tag)
        return -1;

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) return -1;

    int ct_len  = 0;
    int tmp_len = 0;
    int ret     = -1;

    do {
        // Initialise cipher type (no key/IV yet)
        if (EVP_EncryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, NULL, NULL) != 1)
            break;

        // Set IV length — must be done before setting key/IV
        if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN,
                                 IV_LEN, NULL) != 1)
            break;

        // Set key and IV together
        // The IV here is the counter-based nonce generated by the caller
        // via generate_nonce(). We do NOT generate a new IV internally —
        // that was the critical bug in the previous version.
        if (EVP_EncryptInit_ex(ctx, NULL, NULL, key, iv) != 1)
            break;

        // Encrypt plaintext → ciphertext
        if (EVP_EncryptUpdate(ctx, ciphertext, &ct_len,
                              plaintext, pt_len) != 1)
            break;

        // Finalise — GCM typically outputs 0 bytes here, but must be called
        if (EVP_EncryptFinal_ex(ctx, ciphertext + ct_len, &tmp_len) != 1)
            break;
        ct_len += tmp_len;

        // Extract authentication tag
        if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_GET_TAG,
                                 TAG_LEN, tag) != 1)
            break;

        ret = ct_len;   // Success
    } while (0);

    EVP_CIPHER_CTX_free(ctx);
    return ret;
}

// ============================================================================
// AES-256-GCM DECRYPTION
// ============================================================================

int aes_gcm_decrypt(const uint8_t  key[AES_KEY_LEN],
                    const uint8_t *ciphertext, int ct_len,
                    const uint8_t  iv[IV_LEN],
                    const uint8_t  tag[TAG_LEN],
                    uint8_t       *plaintext) {

    if (!key || !ciphertext || ct_len < 0 || !iv || !tag || !plaintext)
        return -1;

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) return -1;

    int pt_len  = 0;
    int tmp_len = 0;
    int ret     = -1;

    do {
        if (EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), NULL, NULL, NULL) != 1)
            break;

        if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN,
                                 IV_LEN, NULL) != 1)
            break;

        if (EVP_DecryptInit_ex(ctx, NULL, NULL, key, iv) != 1)
            break;

        if (EVP_DecryptUpdate(ctx, plaintext, &pt_len,
                              ciphertext, ct_len) != 1)
            break;

        // Set the expected authentication tag BEFORE calling Final.
        // The cast to (void*) is required by the OpenSSL API — the tag
        // is read, not written, despite the non-const pointer.
        if (EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG,
                                 TAG_LEN, (void *)tag) != 1)
            break;

        // DecryptFinal performs the authentication check.
        // Returns 1 on success (tag matches), 0 on authentication failure.
        // This is the only place where the tag is verified — do not skip it.
        if (EVP_DecryptFinal_ex(ctx, plaintext + pt_len, &tmp_len) != 1) {
            // Authentication failed — zero the partial plaintext so
            // unauthenticated data never reaches the caller
            memset(plaintext, 0, (size_t)pt_len);
            ret = -1;
            break;
        }
        pt_len += tmp_len;

        ret = pt_len;   // Success — authenticated and decrypted
    } while (0);

    EVP_CIPHER_CTX_free(ctx);
    return ret;     // -1 on any failure, >= 0 on success
}

// ============================================================================
// FRAMED MESSAGE ENCRYPTION  (handshake layer)
// ============================================================================

int send_encrypted_message(int fd,
                           const uint8_t  key[AES_KEY_LEN],
                           const uint8_t *msg, uint32_t msg_len,
                           double        *enc_time_us) {

    if (msg_len > MAX_MESSAGE_SIZE) return 0;

    // For the handshake channel we generate a fresh random IV per message.
    // This is safe here because the handshake consists of only a handful of
    // messages — the birthday-bound collision risk is negligible.
    // The data tunnel uses counter nonces instead (see vpn_server/client).
    uint8_t iv[IV_LEN];
    if (RAND_bytes(iv, IV_LEN) != 1) return 0;

    uint8_t *ct = malloc(msg_len + 1);   // +1 safety margin
    if (!ct) return 0;

    uint8_t tag[TAG_LEN];

    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    int ct_len = aes_gcm_encrypt(key, msg, (int)msg_len, iv, ct, tag);

    clock_gettime(CLOCK_MONOTONIC, &t1);
    if (enc_time_us) *enc_time_us = elapsed_us(t0, t1);

    if (ct_len < 0) { free(ct); return 0; }

    // Frame: [uint32_t total_len (BE)][IV][TAG][ciphertext]
    uint32_t total  = IV_LEN + TAG_LEN + (uint32_t)ct_len;
    uint32_t net_len = htonl(total);

    int ok = (write_all(fd, &net_len, sizeof(net_len)) > 0 &&
              write_all(fd, iv,       IV_LEN)           > 0 &&
              write_all(fd, tag,      TAG_LEN)           > 0 &&
              write_all(fd, ct,       (size_t)ct_len)    > 0);

    free(ct);
    return ok ? 1 : 0;
}

int recv_encrypted_message(int fd,
                           const uint8_t  key[AES_KEY_LEN],
                           uint8_t      **msg_out, uint32_t *msg_len_out,
                           double        *dec_time_us) {

    // Read 4-byte length prefix
    uint32_t net_len = 0;
    if (read_exact(fd, &net_len, sizeof(net_len)) < 0) return 0;

    uint32_t total = ntohl(net_len);
    if (total < IV_LEN + TAG_LEN || total > MAX_MESSAGE_SIZE) return 0;

    uint8_t  iv[IV_LEN];
    uint8_t  tag[TAG_LEN];
    uint32_t ct_len = total - IV_LEN - TAG_LEN;

    uint8_t *ct = malloc(ct_len);
    if (!ct) return 0;

    if (read_exact(fd, iv,  IV_LEN)  < 0 ||
        read_exact(fd, tag, TAG_LEN) < 0 ||
        read_exact(fd, ct,  ct_len)  < 0) {
        free(ct);
        return 0;
    }

    // Allocate plaintext buffer
    // +1 for null terminator — handshake messages may be treated as strings
    uint8_t *pt = malloc(ct_len + 1);
    if (!pt) { free(ct); return 0; }

    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);

    int pt_len = aes_gcm_decrypt(key, ct, (int)ct_len, iv, tag, pt);

    clock_gettime(CLOCK_MONOTONIC, &t1);
    if (dec_time_us) *dec_time_us = elapsed_us(t0, t1);

    free(ct);

    if (pt_len < 0) {
        free(pt);
        return 0;
    }

    pt[pt_len] = '\0';      // Null-terminate for string safety
    *msg_out     = pt;
    *msg_len_out = (uint32_t)pt_len;
    return 1;
}